// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOefYE0XMzW8Ylm5lkfnGxrySYAWJadwQ',
    appId: '1:1092483099683:web:9a6c111348a3463ed1d596',
    messagingSenderId: '1092483099683',
    projectId: 'newsappmob',
    authDomain: 'newsappmob.firebaseapp.com',
    storageBucket: 'newsappmob.appspot.com',
    measurementId: 'G-MW7K28B7JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMUWM0STIJcN7KnjLKOYMOUJ1LJDv0sAQ',
    appId: '1:1092483099683:android:27f5f2b454fb4707d1d596',
    messagingSenderId: '1092483099683',
    projectId: 'newsappmob',
    storageBucket: 'newsappmob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWu8vEQB8Vrd44By1lb_-5CFXDK_d-DQM',
    appId: '1:1092483099683:ios:6199d5aacb25b822d1d596',
    messagingSenderId: '1092483099683',
    projectId: 'newsappmob',
    storageBucket: 'newsappmob.appspot.com',
    iosClientId: '1092483099683-6m33ghkeuc9dmohrp6n8n87tbat7v7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
